#ifndef __CONST_MENU_GP__
#define __CONST_MENU_GP__

#define EKRAN_TIMEOUT_GP_GROUP1     (EKRAN_TIMEOUT_UMAX_GROUP4 + 1)
#define EKRAN_TIMEOUT_GP_GROUP2     (EKRAN_TIMEOUT_GP_GROUP1 + 1)
#define EKRAN_TIMEOUT_GP_GROUP3     (EKRAN_TIMEOUT_GP_GROUP2 + 1)
#define EKRAN_TIMEOUT_GP_GROUP4     (EKRAN_TIMEOUT_GP_GROUP3 + 1)
#define EKRAN_CONTROL_GP            (EKRAN_CONTROL_KZ_ZV + 1)

enum  _index_ml_tmo_GP
{
  INDEX_ML_TMO_GP1 = 0,
  INDEX_ML_TMO_GP2,
  INDEX_ML_TMO_GP_RPN,
  
  MAX_ROW_FOR_TIMEOUT_GP
};

#define COL_TMO_GP1_BEGIN      4
#define COL_TMO_GP1_COMMA      6
#define COL_TMO_GP1_END        8

#define COL_TMO_GP2_BEGIN      5
#define COL_TMO_GP2_COMMA      6
#define COL_TMO_GP2_END        8

#define COL_TMO_GP_RPN_BEGIN   5
#define COL_TMO_GP_RPN_COMMA   6
#define COL_TMO_GP_RPN_END     8

enum _index_ml_ctrl_GP
{
  INDEX_ML_CTR_GP_STATE = 0,

  MAX_ROW_FOR_CONTROL_GP
};

#define CTR_GP_MASKA             (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_GP) - 1)

#endif
