#ifndef __CONST_MENU_CHOSE_SETTING_PROTECTION__
#define __CONST_MENU_CHOSE_SETTING_PROTECTION__

#define EKRAN_CHOOSE_SETTINGS_OZT                       (EKRAN_RESURS + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_OZT        (EKRAN_CHOOSE_SETTINGS_OZT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_OZT        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_OZT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_OZT        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_OZT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_OZT        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_OZT + 1)
#define EKRAN_CHOOSE_SETTINGS_MTZ                       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_OZT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_MTZ        (EKRAN_CHOOSE_SETTINGS_MTZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_MTZ        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_MTZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_MTZ        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_MTZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_MTZ        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_MTZ + 1)
#define EKRAN_CHOOSE_SETTINGS_TZNP                      (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_MTZ + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_TZNP       (EKRAN_CHOOSE_SETTINGS_TZNP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_TZNP       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_TZNP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_TZNP       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_TZNP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_TZNP       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_TZNP + 1)
#define EKRAN_CHOOSE_SETTINGS_UROV                      (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_TZNP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UROV       (EKRAN_CHOOSE_SETTINGS_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UROV       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UROV       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UROV       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UROV + 1)
#define EKRAN_CHOOSE_SETTINGS_ZOP                       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UROV + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ZOP        (EKRAN_CHOOSE_SETTINGS_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ZOP        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ZOP        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ZOP        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_ZOP + 1)
#define EKRAN_CHOOSE_SETTINGS_UMIN                      (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_ZOP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMIN       (EKRAN_CHOOSE_SETTINGS_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMIN       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMIN       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMIN       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMIN + 1)
#define EKRAN_CHOOSE_SETTINGS_UMAX                      (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMIN + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMAX       (EKRAN_CHOOSE_SETTINGS_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMAX       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMAX       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMAX       (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UMAX + 1)
#define EKRAN_CHOOSE_SETTINGS_IN_OUT                    (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UMAX + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_IN_OUT     (EKRAN_CHOOSE_SETTINGS_IN_OUT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_IN_OUT     (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_IN_OUT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_IN_OUT     (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_IN_OUT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_IN_OUT     (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_IN_OUT + 1)
#define EKRAN_CHOOSE_SETTINGS_GP                        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_IN_OUT + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_GP         (EKRAN_CHOOSE_SETTINGS_GP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_GP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_GP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_GP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_GP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_GP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_GP + 1)
#define EKRAN_CHOOSE_SETTINGS_TP                        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_GP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_TP         (EKRAN_CHOOSE_SETTINGS_TP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_TP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_TP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_TP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_TP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_TP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_TP + 1)
#define EKRAN_CHOOSE_SETTINGS_EP                        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_TP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_EP         (EKRAN_CHOOSE_SETTINGS_EP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_EP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_EP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_EP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_EP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_EP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_EP + 1)
#define EKRAN_CHOOSE_SETTINGS_UP                        (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_EP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UP         (EKRAN_CHOOSE_SETTINGS_UP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP1_UP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP2_UP + 1)
#define EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP4_UP         (EKRAN_CHOOSE_SETPOINT_TIMEOUT_GROUP3_UP + 1)

#define MAX_ROW_FOR_CHOSE_SETTINGS_ANY_PROTECTION                    3
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_TWO_GROUP         (NUMBER_GROUP_USTAVOK + 1)
#define MAX_ROW_FOR_CHOSE_SETPOINTS_TIMEOUTS                         2
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_CONTROL           1
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_TIMEOUT           1
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_TIMEOUT_CONTROL   2
#define MAX_ROW_FOR_CHOSE_SETTINGS_PROTECTION_WITH_SETPOINTS_CONTROL 2

#define INDEX_ML_GROUP1                                   0
#define INDEX_ML_GROUP2                                   1
#define INDEX_ML_GROUP3                                   2
#define INDEX_ML_GROUP4                                   3
#define INDEX_ML_CONTROL_WITH_GROUPS                      4

//Це є основні позиції
#define INDEX_ML_SETPOINT                                 0
#define INDEX_ML_TIMEOUT                                  1
#define INDEX_ML_CONTROL                                  2

//Це є додаткові позиції, якщо вони не співпадають з основними
#define INDEX_ML_WITH_CONTROL_CONTROL                     0
#define INDEX_ML_WITH_TIMEOUT_TIMEOUT                     0
#define INDEX_ML_WITH_TIMEOUT_CONTROL_TIMEOUT             0
#define INDEX_ML_WITH_TIMEOUT_CONTROL_CONTROL             1
#define INDEX_ML_WITH_SETPOINT_CONTROL_SETPOINT           0
#define INDEX_ML_WITH_SETPOINT_CONTROL_CONTROL            1


#endif
