#ifndef __CONST_SETPOINT_INTERVAL__
#define __CONST_SETPOINT_INTERVAL__

#define KOEF_TT_MIN                   1
#define KOEF_TT_MAX                   2000

#define KOEF_TN_MIN                   50
#define KOEF_TN_MAX                   1800

#define SETPOINT_GRUPA_USTAVOK_MIN    1
#define SETPOINT_GRUPA_USTAVOK_MAX    4

enum _type_con_ozt
{
  TYPE_CON_OZT_0 = 0,
  TYPE_CON_OZT_1,
  TYPE_CON_OZT_11,
  
  _N_TYPE_CON_OZT 
};

#define PICKUP_OZT_DELTA_Id_MIN         200
#define PICKUP_OZT_DELTA_Id_MAX         40000

#define PICKUP_OZT_K_MIN                0
#define PICKUP_OZT_K_MAX                1000

#define PICKUP_OZT_Id0_MIN              500
#define PICKUP_OZT_Id0_MAX              10000

#define PICKUP_OZT_Ig0_MIN              500
#define PICKUP_OZT_Ig0_MAX              20000

#define PICKUP_OZT_Kg1_MIN              300
#define PICKUP_OZT_Kg1_MAX              900

#define PICKUP_OZT_Ig_OBM_MIN           2000
#define PICKUP_OZT_Ig_OBM_MAX           80000

#define PICKUP_OZT_Kg2_MIN              0
#define PICKUP_OZT_Kg2_MAX              900

#define PICKUP_OZT_K_AI_MIN             500
#define PICKUP_OZT_K_AI_MAX             10000

#define PICKUP_OZT_K_2I_MIN             0
#define PICKUP_OZT_K_2I_MAX             500

#define PICKUP_OZT_K_5I_MIN             0
#define PICKUP_OZT_K_5I_MAX             500

#define PICKUP_OZT_KP_MIN               50
#define PICKUP_OZT_KP_DEFAULT           95
#define PICKUP_OZT_KP_MAX               98

#define TIMEOUT_OZT1_MIN                0
#define TIMEOUT_OZT1_MAX                32000

#define TIMEOUT_OZT2_MIN                0
#define TIMEOUT_OZT2_MAX                32000

#define TYPE_MTZ_SIMPLE                0
#define TYPE_MTZ_DIRECTIONAL           1
#define TYPE_MTZ_VOLTAGE               2
#define TYPE_MTZ_DEPENDENT_A           3
#define TYPE_MTZ_DEPENDENT_B           4
#define TYPE_MTZ_DEPENDENT_C           5
#define TYPE_MTZ_DEPENDENT_RT_80       6
#define TYPE_MTZ_DEPENDENT_RTV_I       7

#define SETPOINT_MTZ1_MIN             500
#define SETPOINT_MTZ1_MAX             150000

#define SETPOINT_MTZ1_N_VPERED_MIN    500
#define SETPOINT_MTZ1_N_VPERED_MAX    150000

#define SETPOINT_MTZ1_N_NAZAD_MIN    500
#define SETPOINT_MTZ1_N_NAZAD_MAX    150000

#define SETPOINT_MTZ1_ANGLE_MIN      0
#define SETPOINT_MTZ1_ANGLE_MAX      90

#define SETPOINT_MTZ1_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ1_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ1_U_MIN          2000
#define SETPOINT_MTZ1_U_MAX          150000

#define SETPOINT_MTZ2_MIN            500
#define SETPOINT_MTZ2_MAX            150000

#define SETPOINT_MTZ2_N_VPERED_MIN    500
#define SETPOINT_MTZ2_N_VPERED_MAX    150000

#define SETPOINT_MTZ2_N_NAZAD_MIN    500
#define SETPOINT_MTZ2_N_NAZAD_MAX    150000

#define SETPOINT_MTZ2_ANGLE_MIN      0
#define SETPOINT_MTZ2_ANGLE_MAX      90

#define SETPOINT_MTZ2_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ2_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ2_U_MIN          2000
#define SETPOINT_MTZ2_U_MAX          150000

#define SETPOINT_MTZ3_MIN             500
#define SETPOINT_MTZ3_MAX             150000

#define SETPOINT_MTZ3_N_VPERED_MIN    500
#define SETPOINT_MTZ3_N_VPERED_MAX    150000

#define SETPOINT_MTZ3_N_NAZAD_MIN    500
#define SETPOINT_MTZ3_N_NAZAD_MAX    150000

#define SETPOINT_MTZ3_ANGLE_MIN      0
#define SETPOINT_MTZ3_ANGLE_MAX      90

#define SETPOINT_MTZ3_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ3_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ3_U_MIN          2000
#define SETPOINT_MTZ3_U_MAX          150000

#define SETPOINT_MTZ4_MIN             500
#define SETPOINT_MTZ4_MAX             150000

#define SETPOINT_MTZ4_N_VPERED_MIN    500
#define SETPOINT_MTZ4_N_VPERED_MAX    150000

#define SETPOINT_MTZ4_N_NAZAD_MIN    500
#define SETPOINT_MTZ4_N_NAZAD_MAX    150000

#define SETPOINT_MTZ4_ANGLE_MIN      0
#define SETPOINT_MTZ4_ANGLE_MAX      90

#define SETPOINT_MTZ4_PO_NAPRUZI_MIN 500
#define SETPOINT_MTZ4_PO_NAPRUZI_MAX 150000

#define SETPOINT_MTZ4_U_MIN          2000
#define SETPOINT_MTZ4_U_MAX          150000

#define TIMEOUT_MTZ1_MIN                        0
#define TIMEOUT_MTZ1_MAX                        32000

#define TIMEOUT_MTZ1_N_VPERED_MIN               0
#define TIMEOUT_MTZ1_N_VPERED_MAX               32000

#define TIMEOUT_MTZ1_N_NAZAD_MIN                0
#define TIMEOUT_MTZ1_N_NAZAD_MAX                32000

#define TIMEOUT_MTZ1_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ1_PO_NAPRUZI_MAX             32000

#define TIMEOUT_MTZ2_MIN                        0
#define TIMEOUT_MTZ2_MAX                        300000

#define TIMEOUT_MTZ2_PR_MIN                     200
#define TIMEOUT_MTZ2_PR_MAX                     5000

#define TIMEOUT_MTZ2_N_VPERED_MIN               0
#define TIMEOUT_MTZ2_N_VPERED_MAX               300000

#define TIMEOUT_MTZ2_N_VPERED_PR_MIN            200
#define TIMEOUT_MTZ2_N_VPERED_PR_MAX            5000

#define TIMEOUT_MTZ2_N_NAZAD_MIN                0
#define TIMEOUT_MTZ2_N_NAZAD_MAX                300000

#define TIMEOUT_MTZ2_N_NAZAD_PR_MIN             200
#define TIMEOUT_MTZ2_N_NAZAD_PR_MAX             5000

#define TIMEOUT_MTZ2_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ2_PO_NAPRUZI_MAX             300000

#define TIMEOUT_MTZ2_PO_NAPRUZI_PR_MIN          200
#define TIMEOUT_MTZ2_PO_NAPRUZI_PR_MAX          5000

#define TIMEOUT_MTZ2_VVID_PR_MIN                200
#define TIMEOUT_MTZ2_VVID_PR_MAX                5000

#define TIMEOUT_MTZ3_MIN                        0
#define TIMEOUT_MTZ3_MAX                        300000

#define TIMEOUT_MTZ3_N_VPERED_MIN               0
#define TIMEOUT_MTZ3_N_VPERED_MAX               300000

#define TIMEOUT_MTZ3_N_NAZAD_MIN                0
#define TIMEOUT_MTZ3_N_NAZAD_MAX                300000

#define TIMEOUT_MTZ3_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ3_PO_NAPRUZI_MAX             300000

#define TIMEOUT_MTZ4_MIN                        0
#define TIMEOUT_MTZ4_MAX                        300000

#define TIMEOUT_MTZ4_N_VPERED_MIN               0
#define TIMEOUT_MTZ4_N_VPERED_MAX               300000

#define TIMEOUT_MTZ4_N_NAZAD_MIN                0
#define TIMEOUT_MTZ4_N_NAZAD_MAX                300000

#define TIMEOUT_MTZ4_PO_NAPRUZI_MIN             0
#define TIMEOUT_MTZ4_PO_NAPRUZI_MAX             300000

#define SETPOINT_P_3U0_MIN                      5000
#define SETPOINT_P_3U0_MAX                      150000

#define TIMEOUT_P_3U0_MIN                       0
#define TIMEOUT_P_3U0_MAX                       32000

#define SETPOINT_TZNP1_3I0_VPERED_MIN 500
#define SETPOINT_TZNP1_3I0_VPERED_MAX 150000

#define SETPOINT_TZNP1_3U0_VPERED_MIN 5000
#define SETPOINT_TZNP1_3U0_VPERED_MAX 150000

#define SETPOINT_TZNP1_3I0_NAZAD_MIN  500
#define SETPOINT_TZNP1_3I0_NAZAD_MAX  150000

#define SETPOINT_TZNP1_3U0_NAZAD_MIN  5000
#define SETPOINT_TZNP1_3U0_NAZAD_MAX  150000

#define SETPOINT_TZNP1_ANGLE_MIN      0
#define SETPOINT_TZNP1_ANGLE_MAX      90

#define SETPOINT_TZNP2_3I0_VPERED_MIN 500
#define SETPOINT_TZNP2_3I0_VPERED_MAX 150000

#define SETPOINT_TZNP2_3U0_VPERED_MIN 5000
#define SETPOINT_TZNP2_3U0_VPERED_MAX 150000

#define SETPOINT_TZNP2_3I0_NAZAD_MIN  500
#define SETPOINT_TZNP2_3I0_NAZAD_MAX  150000

#define SETPOINT_TZNP2_3U0_NAZAD_MIN  5000
#define SETPOINT_TZNP2_3U0_NAZAD_MAX  150000

#define SETPOINT_TZNP2_ANGLE_MIN      0
#define SETPOINT_TZNP2_ANGLE_MAX      90

#define SETPOINT_TZNP3_3I0_VPERED_MIN 500
#define SETPOINT_TZNP3_3I0_VPERED_MAX 150000

#define SETPOINT_TZNP3_3U0_VPERED_MIN 5000
#define SETPOINT_TZNP3_3U0_VPERED_MAX 150000

#define SETPOINT_TZNP3_3I0_NAZAD_MIN  500
#define SETPOINT_TZNP3_3I0_NAZAD_MAX  150000

#define SETPOINT_TZNP3_3U0_NAZAD_MIN  5000
#define SETPOINT_TZNP3_3U0_NAZAD_MAX  150000

#define SETPOINT_TZNP3_ANGLE_MIN      0
#define SETPOINT_TZNP3_ANGLE_MAX      90

#define SETPOINT_TZNP4_3I0_VPERED_MIN 500
#define SETPOINT_TZNP4_3I0_VPERED_MAX 150000

#define SETPOINT_TZNP4_3U0_VPERED_MIN 5000
#define SETPOINT_TZNP4_3U0_VPERED_MAX 150000

#define SETPOINT_TZNP4_3I0_NAZAD_MIN  500
#define SETPOINT_TZNP4_3I0_NAZAD_MAX  150000

#define SETPOINT_TZNP4_3U0_NAZAD_MIN  5000
#define SETPOINT_TZNP4_3U0_NAZAD_MAX  150000

#define SETPOINT_TZNP4_ANGLE_MIN      0
#define SETPOINT_TZNP4_ANGLE_MAX      90

#define TIMEOUT_TZNP1_VPERED_MIN      0
#define TIMEOUT_TZNP1_VPERED_MAX      32000

#define TIMEOUT_TZNP1_NAZAD_MIN       0
#define TIMEOUT_TZNP1_NAZAD_MAX       32000

#define TIMEOUT_TZNP2_VPERED_MIN      0
#define TIMEOUT_TZNP2_VPERED_MAX      32000

#define TIMEOUT_TZNP2_NAZAD_MIN       0
#define TIMEOUT_TZNP2_NAZAD_MAX       32000

#define TIMEOUT_TZNP3_VPERED_MIN      0
#define TIMEOUT_TZNP3_VPERED_MAX      32000

#define TIMEOUT_TZNP3_NAZAD_MIN       0
#define TIMEOUT_TZNP3_NAZAD_MAX       32000

#define TIMEOUT_TZNP4_VPERED_MIN      0
#define TIMEOUT_TZNP4_VPERED_MAX      32000

#define TIMEOUT_TZNP4_NAZAD_MIN       0
#define TIMEOUT_TZNP4_NAZAD_MAX       32000

#define SETPOINT_UROV_MIN             250
#define SETPOINT_UROV_MAX             5000

#define TIMEOUT_UROV1_MIN             0
#define TIMEOUT_UROV1_MAX             32000

#define TIMEOUT_UROV2_MIN             0
#define TIMEOUT_UROV2_MAX             32000

#define SETPOINT_ZOP_MIN              10
#define SETPOINT_ZOP_MAX              1000

#define TIMEOUT_ZOP_MIN               0
#define TIMEOUT_ZOP_MAX               32000

#define SETPOINT_UMIN1_MIN            5000
#define SETPOINT_UMIN1_MAX            110000

#define SETPOINT_UMIN1_IBLK_MIN       250
#define SETPOINT_UMIN1_IBLK_MAX       5000

#define SETPOINT_UMIN2_MIN            5000
#define SETPOINT_UMIN2_MAX            110000

#define SETPOINT_UMIN2_IBLK_MIN       250
#define SETPOINT_UMIN2_IBLK_MAX       5000

#define TIMEOUT_UMIN1_MIN             100
#define TIMEOUT_UMIN1_MAX             32000

#define TIMEOUT_UMIN2_MIN             100
#define TIMEOUT_UMIN2_MAX             32000

#define SETPOINT_UMAX1_MIN            23000
#define SETPOINT_UMAX1_MAX            140000

#define SETPOINT_UMAX2_MIN            23000
#define SETPOINT_UMAX2_MAX            140000

#define SETPOINT_KP_UMAX_MIN          50
#define SETPOINT_KP_UMAX_DEFAULT      95
#define SETPOINT_KP_UMAX_MAX          96

#define TIMEOUT_UMAX1_MIN             0
#define TIMEOUT_UMAX1_MAX             600000

#define TIMEOUT_UMAX2_MIN             0
#define TIMEOUT_UMAX2_MAX             600000

#define SETPOINT_UP_I_MIN             500
#define SETPOINT_UP_I_MAX             150000

#define SETPOINT_UP_3I0_MIN           10
#define SETPOINT_UP_3I0_MAX           2000

#define SETPOINT_UP_U_MIN             5000
#define SETPOINT_UP_U_MAX             140000

#define SETPOINT_UP_P_MIN             10
#define SETPOINT_UP_P_MAX             2000000

#define SETPOINT_UP_KP_MORE_MIN  50
#define SETPOINT_UP_KP_MORE_MAX  95

#define SETPOINT_UP_KP_LESS_MIN  105
#define SETPOINT_UP_KP_LESS_MAX  150

#define TIMEOUT_UP_MIN                0
#define TIMEOUT_UP_MAX                600000

#define TIMEOUT_SWCH_ON_MIN           150
#define TIMEOUT_SWCH_ON_MAX           5000

#define TIMEOUT_SWCH_OFF_MIN          150
#define TIMEOUT_SWCH_OFF_MAX          5000

#define TIMEOUT_SWCH_UDL_BLK_ON_MIN   0
#define TIMEOUT_SWCH_UDL_BLK_ON_MAX   32000

#define TIMEOUT_PRYVODA_VV_MIN        150
#define TIMEOUT_PRYVODA_VV_MAX        1000

#define KOEF_DOPUSK_DV_POST_MIN       0
#define KOEF_DOPUSK_DV_ZMIN_MIN       20
#define KOEF_DOPUSK_DV_MAX            60

#define TIMEOUT_DEACTIVATION_PASSWORD_OFF       0
#define TIMEOUT_DEACTIVATION_PASSWORD_MIN       30
#define TIMEOUT_DEACTIVATION_PASSWORD_MAX       3600

#define TIMEOUT_NEW_SETTINGS_MIN       60
#define TIMEOUT_NEW_SETTINGS_MAX       3600

#define KOEF_ADDRESS_MIN              1
#define KOEF_ADDRESS_MAX              247

#define MAX_NUMBER_SPEEDS_INTERFACE    7
#define VALUE_SPEED_INTERFACE_MIN      0
#define VALUE_SPEED_INTERFACE_MAX      (MAX_NUMBER_SPEEDS_INTERFACE - 1)

#define MAX_NUMBER_PARE_INTERFACE      3
#define VALUE_PARE_INTERFACE_MIN       0
#define VALUE_PARE_INTERFACE_MAX       (MAX_NUMBER_PARE_INTERFACE - 1)

#define MAX_NUMBER_STOP_BITS_INTERFACE 2
#define VALUE_STOP_BITS_INTERFACE_MIN  0
#define VALUE_STOP_BITS_INTERFACE_MAX  (MAX_NUMBER_STOP_BITS_INTERFACE - 1)

#define VALUE_TIME_OUT_1_INTERFACE_MIN 15
#define VALUE_TIME_OUT_1_INTERFACE_MAX 694

#define VALUE_SETTING_LANGUAGE_MIN    LANGUAGE_RU
#define VALUE_SETTING_LANGUAGE_MAX    LANGUAGE_EN

#define NUMBER_ITERATION_EL_MIN       1
#define NUMBER_ITERATION_EL_MAX       32

#define NUMBER_DEFINED_FUNCTIONS_MIN  0
#define NUMBER_DEFINED_FUNCTIONS_MAX  NUMBER_DEFINED_FUNCTIONS

#define NUMBER_DEFINED_TRIGGERS_MIN   0
#define NUMBER_DEFINED_TRIGGERS_MAX   NUMBER_DEFINED_TRIGGERS

#define NUMBER_DEFINED_AND_MIN        0
#define NUMBER_DEFINED_AND_MAX        NUMBER_DEFINED_AND

#define NUMBER_DEFINED_OR_MIN         0
#define NUMBER_DEFINED_OR_MAX         NUMBER_DEFINED_OR

#define NUMBER_DEFINED_XOR_MIN        0
#define NUMBER_DEFINED_XOR_MAX        NUMBER_DEFINED_XOR

#define NUMBER_DEFINED_NOT_MIN        0
#define NUMBER_DEFINED_NOT_MAX        NUMBER_DEFINED_NOT

#define TIMEOUT_DF_PAUSE_MIN          0
#define TIMEOUT_DF_PAUSE_MAX          600000

#define TIMEOUT_DF_WORK_MIN           0
#define TIMEOUT_DF_WORK_MAX           600000

#define TIMEOUT_PREFAULT_MIN          100
#define TIMEOUT_PREFAULT_MAX          5000

#define TIMEOUT_POSTFAULT_MIN         1000
#define TIMEOUT_POSTFAULT_MAX         25000

#endif
