#ifndef __CONST_MENU_GZ__
#define __CONST_MENU_GZ__

#define EKRAN_TIMEOUT_GZ_GROUP1     (EKRAN_TIMEOUT_UMAX_GROUP4 + 1)
#define EKRAN_TIMEOUT_GZ_GROUP2     (EKRAN_TIMEOUT_GZ_GROUP1 + 1)
#define EKRAN_TIMEOUT_GZ_GROUP3     (EKRAN_TIMEOUT_GZ_GROUP2 + 1)
#define EKRAN_TIMEOUT_GZ_GROUP4     (EKRAN_TIMEOUT_GZ_GROUP3 + 1)
#define EKRAN_CONTROL_GZ            (EKRAN_CONTROL_KZ_ZV + 1)

enum  _index_ml_tmo_GZ
{
  INDEX_ML_TMO_GZ1 = 0,
  INDEX_ML_TMO_GZ2,
  INDEX_ML_TMO_GZ_RPN,
  
  MAX_ROW_FOR_TIMEOUT_GZ
};

#define COL_TMO_GZ1_BEGIN      4
#define COL_TMO_GZ1_COMMA      6
#define COL_TMO_GZ1_END        8

#define COL_TMO_GZ2_BEGIN      5
#define COL_TMO_GZ2_COMMA      6
#define COL_TMO_GZ2_END        8

#define COL_TMO_GZ_RPN_BEGIN   5
#define COL_TMO_GZ_RPN_COMMA   6
#define COL_TMO_GZ_RPN_END     8

enum _index_ml_ctrl_GZ
{
  INDEX_ML_CTR_GZ_STATE = 0,

  MAX_ROW_FOR_CONTROL_GZ
};

#define CTR_GZ_MASKA             (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_GZ) - 1)

#endif
