#ifndef __CONST_MENU_KZ_ZV__
#define __CONST_MENU_KZ_ZV__

#define EKRAN_SETPOINT_KZ_ZV_GROUP1 (EKRAN_SETPOINT_UMAX_GROUP4 + 1)
#define EKRAN_SETPOINT_KZ_ZV_GROUP2 (EKRAN_SETPOINT_KZ_ZV_GROUP1 + 1)
#define EKRAN_SETPOINT_KZ_ZV_GROUP3 (EKRAN_SETPOINT_KZ_ZV_GROUP2 + 1)
#define EKRAN_SETPOINT_KZ_ZV_GROUP4 (EKRAN_SETPOINT_KZ_ZV_GROUP3 + 1)
#define EKRAN_CONTROL_KZ_ZV         (EKRAN_CONTROL_UMAX  + 1)

enum  _index_ml_stp_kz_zv
{
  INDEX_ML_STP_KZ_ZV = 0,
  INDEX_ML_STP_KZ_ZV_ANGLE,
  
  MAX_ROW_FOR_SETPOINT_KZ_ZV
};

#define COL_SETPOINT_KZ_ZV_BEGIN    4
#define COL_SETPOINT_KZ_ZV_COMMA    5
#define COL_SETPOINT_KZ_ZV_END      8

#define COL_SETPOINT_KZ_ZV_ANGLE_BEGIN         6
#define COL_SETPOINT_KZ_ZV_ANGLE_END           7

enum _index_ml_ctrl_kz_zv
{
  INDEX_ML_CTR_KZ_ZV_STATE = 0,

  MAX_ROW_FOR_CONTROL_KZ_ZV
};

#define CTR_KZ_ZV_MASKA             (MASKA_FOR_BIT(MAX_ROW_FOR_CONTROL_KZ_ZV) - 1)

#endif
