#ifndef __CONST_MENU_MAIN__
#define __CONST_MENU_MAIN__

#define EKRAN_MAIN              (EKRAN_LEVEL_PASSWORD_HARD + 1)

enum __index_ml1
{
INDEX_ML1_TIME = 0,
INDEX_ML1_MEASURMENTS,
INDEX_ML1_INPUTS_OUTPUTS,
INDEX_ML1_REGISTRATORS,
INDEX_ML1_LANGUAGE,
INDEX_ML1_SETTINGS,
INDEX_ML1_DIAGNOSTYKA,
INDEX_ML1_KONF,
INDEX_ML1_OZT,
INDEX_ML1_MTZ,
INDEX_ML1_P_3U0,
INDEX_ML1_TZNP,
INDEX_ML1_UROV,
INDEX_ML1_ZOP,
INDEX_ML1_UMIN,
INDEX_ML1_UMAX,
INDEX_ML1_IN_OUT,
INDEX_ML1_GP,
INDEX_ML1_TP,
INDEX_ML1_UP,

MAX_ROW_FOR_EKRAN_MAIN
};

#endif
